import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import 'bootstrap/dist/css/bootstrap.min.css';
// import BootstrapJs from "@/components/BootstrapJs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      {/* <BootstrapJs/> */}
        </body>
    </html>
  );
}
